#!/bin/sh
# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

################################################################################
########### Define Constants ###################################################
################################################################################

# Set shortcut mod key
set $mod Mod4

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# Font for window titles
font pango:JetBrainsMono NFM 9


################################################################################
########### Define Shortcuts ###################################################
################################################################################

# Use pactl to adjust volume in PulseAudio.
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle

# start a terminal
bindsym $mod+Return exec --no-startup-id kitty

# kill focused window
bindsym $mod+Shift+q kill

# change focus
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
# resize
bindsym $mod+r mode "resize"

# Open shut down, restart and locking menu
bindsym $mod+0 exec --no-startup-id ~/.config/rofi/scripts/power_menu.sh -no-fixed-num-lines

# Manually re-run monitor setup (e.g. after hot-plugging a screen)
bindsym $mod+Shift+m exec --no-startup-id ~/.config/i3/scripts/setup_monitors.sh

bindsym $mod+d exec --no-startup-id SUDO_ASKPASS=~/.config/rofi/scripts/askpass-rofi.sh rofi -show drun -theme '~/.config/rofi/app_launcher.rasi'
### run
bindsym $mod+Shift+d exec --no-startup-id SUDO_ASKPASS=~/.config/rofi/scripts/askpass-rofi.sh rofi -show run -theme '~/.config/rofi/app_launcher.rasi'
### files
bindsym $mod+Shift+f exec --no-startup-id rofi -show filebrowser -theme '~/.config/rofi/app_launcher.rasi'

############## resize window (you can also use the mouse for that) #############
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

################################################################################
########### Workspace Settings #################################################
################################################################################

# Workspaces are tabbed by default
workspace_layout tabbed

################################ Window Colors #################################
### class               border  backgr. text    indctr. child_border
client.focused          #9e4a59 #680d18 #ffffff #fff066 #9d1c33
client.focused_inactive #333333 #ba868a #000000 #484e50 #680d18
client.unfocused        #333333 #2d0807 #888888 #292d2e #2d0807
client.urgent           #edc96b #fff066 #000000 #fff066 #fff066

##################### Workspace-to-output assignments #########################
# Generated dynamically by setup_monitors.sh — do not add static assignments here.
# On first boot before the script has run, this file may not exist yet; i3
# will simply assign workspaces to whatever outputs are available.
include ~/.config/i3/scripts/workspace_outputs.conf

####################### Open apps in specific workspaces #######################
### Left
assign [class="kitty"] 1
assign [class="org.gnome.Nautilus"] 4

### Center
assign [class="Vivaldi"] 2
assign [class="firefox"] 2
assign [class="Chrome"] 2
assign [class="google-chrome"] 2
assign [class="Code"] 5
assign [class="steam"] 8

### Right
assign [class="Slack"] 3
assign [class="discord"] 3
assign [class="obsidian"] 3
assign [class="todoist"] 3
assign [class="Spotify"] 6
assign [class="Baobab"] 9
assign [class="gnome-system-monitor"] 9

################################################################################
########### Start up execs #####################################################
################################################################################

# Monitor setup: detects outputs, writes workspace_outputs.conf, runs xrandr,
# waits for settle, restores wallpaper and polybar, reloads i3 if conf changed.
exec_always --no-startup-id ~/.config/i3/scripts/setup_monitors.sh

# exec_always --no-startup-id ~/.config/picom/start_picom.sh
exec_always --no-startup-id dunst --config ~/.config/dunst/dunstrc

# Restore/start wallpaper manager (nitrogen) and picom
exec_always --no-startup-id ~/.config/picom/start_picom.sh &
exec_always --no-startup-id nitrogen --restore

# Start polybar (Status bar)
# exec_always --no-startup-id ~/.config/polybar/launch.sh

# Set volume to 50%
exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ 50%

# Set keyboard layout to us intl
exec_always --no-startup-id setxkbmap us intl

# Enable touchpad tapping
exec_always --no-startup-id xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

# Open default windows
exec --no-startup-id kitty
exec --no-startup-id gnome-system-monitor
exec --no-startup-id nautilus
exec --no-startup-id firefox
# exec --no-startup-id obsidian
# exec --no-startup-id todoist
# exec --no-startup-id code ./Documents/dotfiles # only for testing and debugging