#!/bin/bash
# ~/.config/i3/scripts/setup_monitors.sh
#
# 1. Detects connected monitors by connection type (no hard-coded names)
# 2. Writes ~/.config/i3/scripts/workspace_outputs.conf with correct output names
# 3. Runs xrandr to position them
# 4. Waits for the layout to settle (fixes the blank-screen race condition)
# 5. Restores wallpaper and restarts polybar
# 6. Calls `i3-msg reload` only if the workspace conf changed, which is what
#    picks up the new workspace-to-output assignments. Checking for a content
#    change before reloading is what prevents an infinite exec_always loop.

SCRIPT_DIR="$(cd "$(dirname "$BASH_SOURCE")" && pwd)"
WORKSPACE_CONF="$SCRIPT_DIR/workspace_outputs.conf"

# ── 1. Detect monitors ────────────────────────────────────────────────────────
source "$SCRIPT_DIR/get_monitors.sh"

# ── 2. Generate workspace-to-output assignments ───────────────────────────────
# Each workspace line lists its preferred output first, then eDP-1 as a
# fallback so workspaces always land somewhere if an external monitor is absent.
generate_workspace_conf() {
    local left="${LEFT_MON:-}"
    local int="${INT_MON:-eDP-1}"
    local right="${RIGHT_MON:-}"

    {
        echo "# Auto-generated by setup_monitors.sh on $(date)"
        echo "# Do not edit — changes will be overwritten on next monitor setup."
        echo ""

        if [ -n "$left" ]; then
            echo "workspace 1 output $left $int"
            echo "workspace 4 output $left $int"
            echo "workspace 7 output $left $int"
        else
            echo "workspace 1 output $int"
            echo "workspace 4 output $int"
            echo "workspace 7 output $int"
        fi

        echo "workspace 2 output $int"
        echo "workspace 5 output $int"
        echo "workspace 8 output $int"

        if [ -n "$right" ]; then
            echo "workspace 3 output $right $int"
            echo "workspace 6 output $right $int"
            echo "workspace 9 output $right $int"
        else
            echo "workspace 3 output $int"
            echo "workspace 6 output $int"
            echo "workspace 9 output $int"
        fi
    }
}

# Compare against what's on disk, ignoring the datestamp comment line
strip_date() { grep -v '^# Auto-generated'; }

OLD=$(strip_date < "$WORKSPACE_CONF" 2>/dev/null)
NEW=$(generate_workspace_conf | strip_date)

CONF_CHANGED=false
if [ "$OLD" != "$NEW" ]; then
    generate_workspace_conf > "$WORKSPACE_CONF"
    CONF_CHANGED=true
fi

# ── 3. Build and run the xrandr command ──────────────────────────────────────
XRANDR_CMD="xrandr"

[ -n "$INT_MON"   ] && XRANDR_CMD+=" --output $INT_MON --auto --primary"
[ -n "$LEFT_MON"  ] && XRANDR_CMD+=" --output $LEFT_MON --auto --left-of ${INT_MON:-$RIGHT_MON}"
[ -n "$RIGHT_MON" ] && XRANDR_CMD+=" --output $RIGHT_MON --auto --right-of ${INT_MON:-$LEFT_MON}"

# Explicitly disable disconnected outputs to prevent ghost monitors
while IFS= read -r output; do
    XRANDR_CMD+=" --output $output --off"
done < <(xrandr --query | awk '/ disconnected/{print $1}')

if ! eval "$XRANDR_CMD"; then
    notify-send -u critical "i3 monitor setup" \
        "xrandr failed. Run ~/.config/i3/scripts/setup_monitors.sh manually to debug."
    exit 1
fi

# ── 4. Wait for the mode-set to complete before restoring visuals ─────────────
# xrandr returns before the kernel finishes reconfiguring the outputs.
# nitrogen and polybar need the final geometry or they render to a blank screen.
sleep 1

# ── 5. Restore wallpaper and polybar ─────────────────────────────────────────
nitrogen --restore &
~/.config/polybar/launch.sh &

# ── 6. Reload i3 to pick up changed workspace assignments ────────────────────
# Only triggered when the conf file actually changed, which breaks the loop:
# the reload re-runs this script via exec_always, but the second run finds
# identical conf content and skips the reload, stopping the chain.
if $CONF_CHANGED; then
    sleep 0.5  # give i3 a moment after polybar/nitrogen before reloading
    i3-msg reload
fi
